import {IpApiResponse} from "./typings";

export const mockResponse : IpApiResponse = {
    "ip": "206.117.31.142",
    "network": "206.117.31.0/24",
    "version": "IPv4",
    "city": "Sunnyvale",
    "region": "California",
    "region_code": "CA",
    "country": "US",
    "country_name": "United States",
    "country_code": "US",
    "country_code_iso3": "USA",
    "country_capital": "Washington",
    "country_tld": ".us",
    "continent_code": "NA",
    "in_eu": false,
    "postal": "94087",
    "latitude": 37.3502,
    "longitude": -122.0349,
    "timezone": "America/Los_Angeles",
    "utc_offset": "-0700",
    "country_calling_code": "+1",
    "currency": "USD",
    "currency_name": "Dollar",
    "languages": "en-US,es-US,haw,fr",
    "country_area": 9629091.0,
    "country_population": 327167434,
    "asn": "AS4",
    "org": "ISI-AS"
}